/**
 * Tests for drawing from a pre-computed layout (e.g. one generated by RDKit)
 * instead of running the automatic layout algorithm - see
 * DrawerBase.applyPresetLayout() / SmilesDrawer.drawFromLayout().
 */
import {describe, it, expect, vi} from 'vitest';
import {createJSDOM}              from '../helpers';

import SmilesDrawer from '../../src/SmilesDrawer.js';

// A simple 3-heavy-atom layout (ethanol, CCO) with a known right-angle
// geometry and both bonds the same pixel length, so the scale factor and
// relative arrangement are easy to check.
const ethanolLayout = {
    version: 1,
    smiles:  'CCO',
    atoms: [
        {atom_index: 0, element: 'C', x: 0,   y: 0},
        {atom_index: 1, element: 'C', x: 100, y: 0},
        {atom_index: 2, element: 'O', x: 100, y: 100},
    ],
    bonds: [
        {begin_atom_index: 0, end_atom_index: 1, order: 'single', stereo: 'none'},
        {begin_atom_index: 1, end_atom_index: 2, order: 'single', stereo: 'none'},
    ],
};

// A stereocenter (atom 2, `[C@@H]`) whose three heavy substituents (N, Br,
// Cl) are placed symmetrically around it so their centroid coincides
// exactly with the stereocenter - the same degenerate case that made
// applyPresetLayout()'s centroid-direction heuristic pick an arbitrary
// direction for the synthesized implicit hydrogen in the real bug report
// (decimer's layout JSON never includes that hydrogen, since RDKit only
// exports heavy atoms). `F` sits exactly on the spot that heuristic falls
// back to (stereocenter position + (bondLength, 0)), reproducing the
// hydrogen landing on top of an unrelated real atom.
const stereoLayout = {
    version: 1,
    smiles:  'N(F)[C@@H](Br)Cl',
    atoms: [
        {atom_index: 0, element: 'N',  x: 0,                    y: 30},
        {atom_index: 1, element: 'F',  x: 33.797958971132715,   y: 0},
        {atom_index: 2, element: 'C',  x: 0,                    y: 0},
        {atom_index: 3, element: 'Br', x: -25.980762113533157,  y: -15},
        {atom_index: 4, element: 'Cl', x: 25.980762113533153,   y: -15},
    ],
    bonds: [
        {begin_atom_index: 0, end_atom_index: 1, order: 'single', stereo: 'none'},
        {begin_atom_index: 0, end_atom_index: 2, order: 'single', stereo: 'none'},
        {begin_atom_index: 2, end_atom_index: 3, order: 'single', stereo: 'none'},
        {begin_atom_index: 2, end_atom_index: 4, order: 'single', stereo: 'none'},
    ],
};

// The same symmetric-substituent shape as stereoLayout above, but without a
// decoy atom: the three real heavy substituents (N, Br, Cl) sit exactly 120
// degrees apart around the stereocenter, so their centroid coincides with
// it - the case that degenerated the old centroid-direction heuristic into a
// fixed, arbitrary placement direction. Unlike stereoLayout's contrived F
// marker, this reproduces a real report: with @rdkit/rdkit's CoordGen layout
// for a large fused-ring molecule, that fixed direction landed the
// synthesized hydrogen close enough to a genuine ring nitrogen (about a
// third of a bond length away) to be hard to tell apart on screen, without
// tripping resolvePresetOverlap()'s glyph-overlap threshold. See
// DrawerBase.applyPresetLayout()'s largest-gap-bisector placement.
const symmetricStereoLayout = {
    version: 1,
    smiles:  'N[C@@H](Br)Cl',
    atoms: [
        {atom_index: 0, element: 'N',  x: 100, y: 0},
        {atom_index: 1, element: 'C',  x: 0,   y: 0},
        {atom_index: 2, element: 'Br', x: -50, y: 86.60254037844386},
        {atom_index: 3, element: 'Cl', x: -50, y: -86.60254037844386},
    ],
    bonds: [
        {begin_atom_index: 0, end_atom_index: 1, order: 'single', stereo: 'none'},
        {begin_atom_index: 1, end_atom_index: 2, order: 'single', stereo: 'none'},
        {begin_atom_index: 1, end_atom_index: 3, order: 'single', stereo: 'none'},
    ],
};

describe('drawFromLayout', () => {
    it('applies the preset atom positions instead of the automatic layout', () => {
        createJSDOM();
        const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

        const smilesDrawer = new SmilesDrawer();
        let drawnSvg = null;
        smilesDrawer.drawFromLayout(ethanolLayout, 'svg', 'light', (svg) => {
            drawnSvg = svg;
        });

        expect(drawnSvg).not.toBeNull();
        // No atom-count/element mismatch, so it should not have fallen back
        // to the automatic layout.
        expect(warnSpy).not.toHaveBeenCalled();

        const vertices = smilesDrawer.drawer.preprocessor.graph.vertices;
        const bondLength = smilesDrawer.drawer.opts.bondLength;

        expect(vertices).toHaveLength(3);

        // Both source bonds were the same pixel length, so both should be
        // scaled to exactly opts.bondLength.
        expect(vertices[0].position.distance(vertices[1].position)).toBeCloseTo(bondLength, 5);
        expect(vertices[1].position.distance(vertices[2].position)).toBeCloseTo(bondLength, 5);

        // The source geometry is a right angle (bond 0->1 horizontal, bond
        // 1->2 vertical, same winding as the input) - relative arrangement
        // should be preserved, not recomputed by the automatic layout.
        const v01x = vertices[1].position.x - vertices[0].position.x;
        const v01y = vertices[1].position.y - vertices[0].position.y;
        const v12x = vertices[2].position.x - vertices[1].position.x;
        const v12y = vertices[2].position.y - vertices[1].position.y;
        const dot = v01x * v12x + v01y * v12y;
        expect(dot).toBeCloseTo(0, 5);

        warnSpy.mockRestore();
    });

    it('falls back to the automatic layout on an atom count mismatch', () => {
        createJSDOM();
        const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

        const badLayout = {
            ...ethanolLayout,
            atoms: ethanolLayout.atoms.slice(0, 2),
        };

        const smilesDrawer = new SmilesDrawer();
        let drawnSvg = null;
        smilesDrawer.drawFromLayout(badLayout, 'svg', 'light', (svg) => {
            drawnSvg = svg;
        });

        expect(drawnSvg).not.toBeNull();
        expect(warnSpy).toHaveBeenCalled();

        const vertices = smilesDrawer.drawer.preprocessor.graph.vertices;
        expect(vertices).toHaveLength(3);
        // Fell back to the automatic layout, so all vertices should still
        // end up positioned (not stuck at the default (0,0)).
        expect(vertices.every(v => v.positioned)).toBe(true);

        warnSpy.mockRestore();
    });

    it('does not draw a stereocenter\'s synthesized implicit hydrogen on top of another atom', () => {
        createJSDOM();
        const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

        // compactDrawing is disabled: this molecule's stereocenter has two
        // terminal heteroatom substituents (Br, Cl), which otherwise trips
        // initPseudoElements()'s unrelated "collapse terminal heteroatoms
        // into the parent's label" heuristic and hides them - masking the
        // collision this test exists to catch.
        const smilesDrawer = new SmilesDrawer({compactDrawing: false});
        let drawnSvg = null;
        smilesDrawer.drawFromLayout(stereoLayout, 'svg', 'light', (svg) => {
            drawnSvg = svg;
        });

        expect(drawnSvg).not.toBeNull();
        expect(warnSpy).not.toHaveBeenCalled();

        const vertices = smilesDrawer.drawer.preprocessor.graph.vertices;
        const bondLength = smilesDrawer.drawer.opts.bondLength;

        // One extra vertex beyond the 5 layout atoms: the stereocenter's
        // synthesized implicit hydrogen.
        expect(vertices).toHaveLength(6);

        const drawn = vertices.filter(v => v.value.isDrawn);
        for (let i = 0; i < drawn.length; i++) {
            for (let j = i + 1; j < drawn.length; j++) {
                expect(drawn[i].position.distance(drawn[j].position)).toBeGreaterThan(0.1 * bondLength);
            }
        }

        warnSpy.mockRestore();
    });

    it('places a symmetric stereocenter\'s synthesized hydrogen well clear of every real substituent', () => {
        createJSDOM();
        const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

        const smilesDrawer = new SmilesDrawer({compactDrawing: false});
        let drawnSvg = null;
        smilesDrawer.drawFromLayout(symmetricStereoLayout, 'svg', 'light', (svg) => {
            drawnSvg = svg;
        });

        expect(drawnSvg).not.toBeNull();
        expect(warnSpy).not.toHaveBeenCalled();

        const vertices = smilesDrawer.drawer.preprocessor.graph.vertices;
        const bondLength = smilesDrawer.drawer.opts.bondLength;

        // One extra vertex beyond the 4 layout atoms: the stereocenter's
        // synthesized implicit hydrogen.
        expect(vertices).toHaveLength(5);

        const hydrogen = vertices.find(v => v.value.element === 'H');
        const heavyVertices = vertices.filter(v => v !== hydrogen);

        // The old centroid-direction heuristic placed the hydrogen directly on
        // top of the N substituent in this exact shape (distance ~0); the
        // largest-gap-bisector placement puts it bondLength away from its two
        // nearest real neighbours and 2*bondLength from the third, so every
        // heavy substituent should be comfortably far, not just non-overlapping.
        for (const heavy of heavyVertices) {
            expect(hydrogen.position.distance(heavy.position)).toBeGreaterThan(0.9 * bondLength);
        }

        warnSpy.mockRestore();
    });
});
